import type { NextPage } from "next";
import Head from "next/head";
import { io } from "socket.io-client";

const socket = io("http://localhost:3001");

socket.on("hello", (data) => {
  console.log("data", data);
});

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen bg-zinc-800 text-white">
        <h1 className="">Planning poker</h1>
      </main>
    </div>
  );
};

export default Home;
